# Generated by Django 5.0 on 2024-01-03 08:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the client's name.", max_length=25, verbose_name='Name')),
                ('surname', models.CharField(help_text="Enter the client's surname.", max_length=25, verbose_name='Surname')),
                ('phone_number', models.CharField(help_text="Enter the client's phone number.", max_length=150, verbose_name='Phone Number')),
                ('reg_date', models.DateField(auto_now_add=True, verbose_name='Registration Date')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Payment Type')),
                ('reg_date', models.DateField(auto_now_add=True, verbose_name='Registration Date')),
            ],
            options={
                'verbose_name': 'Payment Type',
                'verbose_name_plural': 'Payment Types',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the product name.', max_length=255, verbose_name='Product Name')),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the product price.', max_digits=10, verbose_name='Price')),
                ('quantity_on_hand', models.IntegerField(default=0, help_text='Enter the quantity on hand.', verbose_name='Quantity on Hand')),
                ('shtrix', models.CharField(blank=True, max_length=150, unique=True, verbose_name='Product Shtrix')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='DragAndDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the request title.', max_length=150, verbose_name='Title')),
                ('special_key', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Special key:')),
                ('reg_date', models.DateField(auto_now_add=True, verbose_name='Registration Date')),
                ('clients', models.ManyToManyField(blank=True, help_text='Select clients', to='main.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Drag And Drop',
                'verbose_name_plural': 'Drag And Drops',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the client's name.", max_length=150, verbose_name='Client Name')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Enter the payment amount.', max_digits=25, verbose_name='Amount')),
                ('id_payment', models.CharField(blank=True, help_text='Unique ID for the payment', max_length=150, unique=True, verbose_name='ID Payment')),
                ('reg_date', models.DateField(auto_now_add=True, verbose_name='Registration Date')),
                ('payment_type', models.ForeignKey(help_text='Select payment type', on_delete=django.db.models.deletion.CASCADE, to='main.paymenttype', verbose_name='Payment Type')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='PayProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the client's name.", max_length=25, verbose_name='Client Name')),
                ('quantity', models.IntegerField(default=0, help_text='Enter the quantity.', verbose_name='Quantity')),
                ('price', models.IntegerField(default=0, help_text='Enter the price.', verbose_name='Price')),
                ('pay_date', models.DateField(auto_now_add=True, verbose_name='Payment Date')),
                ('id_payment', models.CharField(blank=True, help_text='Unique ID for the payment', max_length=150, unique=True, verbose_name='ID Payment')),
                ('product', models.ForeignKey(help_text='Select product', on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Pay Product',
                'verbose_name_plural': 'Pay Products',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.IntegerField(help_text='Enter the quantity sold.', verbose_name='Quantity Sold')),
                ('sale_date', models.DateTimeField(auto_now_add=True, verbose_name='Sale Date')),
                ('product', models.ForeignKey(help_text='Select product', on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
            },
        ),
    ]
