# Generated by Django 5.0 on 2024-01-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draganddrop',
            name='title_en',
            field=models.CharField(help_text='Enter the request title.', max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='draganddrop',
            name='title_ru',
            field=models.CharField(help_text='Enter the request title.', max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='draganddrop',
            name='title_uz',
            field=models.CharField(help_text='Enter the request title.', max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='payment',
            name='name_en',
            field=models.CharField(help_text="Enter the client's name.", max_length=150, null=True, verbose_name='Client Name'),
        ),
        migrations.AddField(
            model_name='payment',
            name='name_ru',
            field=models.CharField(help_text="Enter the client's name.", max_length=150, null=True, verbose_name='Client Name'),
        ),
        migrations.AddField(
            model_name='payment',
            name='name_uz',
            field=models.CharField(help_text="Enter the client's name.", max_length=150, null=True, verbose_name='Client Name'),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Payment Type'),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Payment Type'),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='title_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Payment Type'),
        ),
        migrations.AddField(
            model_name='payproduct',
            name='name_en',
            field=models.CharField(help_text="Enter the client's name.", max_length=25, null=True, verbose_name='Client Name'),
        ),
        migrations.AddField(
            model_name='payproduct',
            name='name_ru',
            field=models.CharField(help_text="Enter the client's name.", max_length=25, null=True, verbose_name='Client Name'),
        ),
        migrations.AddField(
            model_name='payproduct',
            name='name_uz',
            field=models.CharField(help_text="Enter the client's name.", max_length=25, null=True, verbose_name='Client Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(help_text='Enter the product name.', max_length=255, null=True, verbose_name='Product Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(help_text='Enter the product name.', max_length=255, null=True, verbose_name='Product Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(help_text='Enter the product name.', max_length=255, null=True, verbose_name='Product Name'),
        ),
    ]
