# Generated by Django 5.0 on 2024-01-03 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_draganddrop_title_en_draganddrop_title_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='payproduct',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='payproduct',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='payproduct',
            name='name_uz',
        ),
    ]
