# Generated by Django 5.0 on 2024-01-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_payment_name_en_remove_payment_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draganddrop',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='draganddrop',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='draganddrop',
            name='title_uz',
        ),
        migrations.RemoveField(
            model_name='paymenttype',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='paymenttype',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='paymenttype',
            name='title_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_uz',
        ),
    ]
