# Generated by Django 5.0 on 2024-01-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_draganddrop_title_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the client's name.", max_length=150, verbose_name='Client Name')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Enter the payment amount.', max_digits=25, verbose_name='Amount')),
                ('id_payment', models.CharField(blank=True, help_text='Unique ID for the payment', max_length=150, unique=True, verbose_name='ID Payment')),
                ('reg_date', models.DateField(auto_now_add=True, verbose_name='Registration Date')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentType',
        ),
    ]
